"""Adding unique constraints to Place place-type

Revision ID: 0d554d911417
Revises: 3bb503143b16
Create Date: 2025-03-19 11:36:37.318940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d554d911417'
down_revision: Union[str, None] = '3bb503143b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place') as batch_op:
        batch_op.create_unique_constraint("uq_place_name_place_type", ['name', 'place_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place') as batch_op:
        batch_op.drop_constraint("uq_place_name_place_type", type_='unique')
    # ### end Alembic commands ###
