"""Adding enable to account_role table

Revision ID: 903cd5116e1a
Revises: 2399106e832f
Create Date: 2025-03-26 18:51:24.895385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '903cd5116e1a'
down_revision: Union[str, None] = '2399106e832f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_role') as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False))
        # batch_op.drop_constraint("foreign_", type_='foreignkey')
        batch_op.create_foreign_key("account_id_", 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_role') as batch_op:
        # batch_op.drop_constraint("foreign_", type_='foreignkey')
        batch_op.create_foreign_key("account_id_", 'account', ['account_id'], ['id'])
        batch_op.drop_column('enabled')
    # ### end Alembic commands ###
